sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t javo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true javo/react-test npm test

after_success:
  - docker build -t javonexas/multi-client ./client
  - docker build -t javonexas/multi-nginx ./nginx
  - docker build -t javonexas/multi-serve ./server
  - docker build -t javonexas/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker
  - docker push javonexas/multi-client
  - docker push javonexas/multi-nginx
  - docker push javonexas/multi-server
  - docker push javonexas/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-660560547527
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY